# Generated by Django 3.0.3 on 2020-03-22 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radical',
            name='wordId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eva.Word'),
        ),
    ]
