# Generated by Django 3.0.3 on 2020-03-23 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import eva.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eva', '0003_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='wordId',
            new_name='workId',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=eva.models.file_rename),
        ),
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('review', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=150)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
